name: WorldGuardBlockCommands
author: Bobcatsss
version: 0.1
api-version: 1.13
depend: [WorldGuard, WorldEdit]
main: me.bobcatsss.worldguardblockcommands.WorldGuardBlockCommands
commands:
  worldguardblockcommands:
    description: Reload command.
